# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



platform :ios do
  desc "build"
  lane :custom_lane do
    # increment_build_number(xcodeproj: "./trylane.xcodeproj")
    
    # increment_build_number(xcodeproj: "./trylane.xcodeproj",version_number:99)
    increment_version_number( xcodeproj: "./trylane.xcodeproj", version_number: "0") 

   
    # add actions here: https://docs.fastlane.tools/actions
  end
end



platform :android do
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: '../android/')
    gradle(task: "assemble",build_type: "Release",project_dir:'../android/')
    
    # gradle(task: values[:type], build_type: 'Release', project_dir: '../android/app/')
    
  end


end