# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "ios build"
  lane :custom_lane do

    increment_build_number(xcodeproj: "./trylane.xcodeproj")

    # build_app(workspace: "./ios/AffiliateApp.xcworkspace", scheme: "AffiliateApp")
    # add actions here: https://docs.fastlane.tools/actions
  end
end
